# Generated by Django 3.0.4 on 2020-04-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='modality',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
