# Generated by Django 3.0.3 on 2020-02-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('duration', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(related_name='services', to='services.Services')),
            ],
        ),
    ]
