# Generated by Django 3.0.4 on 2020-04-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='duration',
            field=models.IntegerField(max_length=20),
        ),
    ]
